#!/usr/bin/env python3
"""Measure the SEO shape of every article and write docs/keywords.md.

WHY THIS EXISTS
---------------
The owner asked which phrases we are targeting, how often each one is used,
and how the pages link to each other. Answering that from memory is how a
content plan starts drifting from the content: an article gets rewritten, its
keyword moves, and the list still says what was true in September.

So the list is generated. Every number in docs/keywords.md is read out of the
Markdown at the moment the file is written, and the file is regenerated by the
same workflow that publishes. If an article changes, the table changes with
it.

WHAT IT MEASURES, AND WHY EACH ONE
----------------------------------
* occurrences — how many times the target phrase appears in the body. Fewer
  than two and the page is not clearly about it. Density is reported next to
  it because a number without its denominator invites stuffing.

* density — occurrences as a share of words. Google has said for years that
  there is no target density and no threshold that helps. It is here as a
  ceiling, not a goal: past roughly 2.5% a Persian page starts reading like it
  was written for a crawler, and readers leave. Under that, ignore it.

* in title / in description / early — whether the phrase is in the places a
  searcher actually sees before clicking, and in the opening where a reader
  decides the page answers their question.

* links out / links in — internal links, counted in both directions. The
  second number is the one nobody tracks and the one that matters: a page no
  other page links to is reachable only from the sitemap, and gets crawled
  and re-crawled last.

Run: python3 tools/seo_report.py [--check]
  --check  print the report and fail if an article breaks a rule
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import build_content as bc  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "keywords.md"

# Density past this reads as written-for-the-crawler. It is a ceiling with no
# matching floor, because there is no evidence a floor helps anything.
DENSITY_CEILING = 2.5
MIN_OCCURRENCES = 2
MIN_LINKS_OUT = 2
# The opening where a reader decides whether the page is about their question.
EARLY_WORDS = 150

# Internal links are written both ways in the existing articles — as a path
# and as a full https://vandidad.xyz/... address. Both are internal links and
# both must be counted, or the report says a page has none when it has two.
LINK_RE = re.compile(
    r"\[([^\]]+)\]\((?:https?://(?:www\.)?vandidad\.xyz)?(/[^)]*)\)")


def _words(text: str) -> list[str]:
    return [w for w in re.sub(r"[#*_`>\[\]()!-]", " ", text).split() if w.strip()]


def occurrences(haystack: str, phrase: str) -> int:
    """Count the phrase the way a reader would hear it, not byte for byte.

    Folding runs through the same normaliser the duplicate check uses, so
    «چت‌بات» and «چت بات» are one phrase here exactly as they are there.
    """
    if not phrase:
        return 0
    hay = bc._norm_keyword(haystack)
    needle = bc._norm_keyword(phrase)
    if not needle:
        return 0
    return len(re.findall(re.escape(needle), hay))


class Report:
    def __init__(self, article: bc.Article, state: str, goes_live):
        self.a = article
        self.state = state  # منتشرشده / در صف
        # The day this page starts existing for a reader: the publication date
        # for a live article, the queued publish_on for one still waiting.
        # Linking is only safe backwards along this date.
        self.goes_live = goes_live
        body = article.body_md
        self.words = article.words
        self.kw = article.target_keyword
        self.hits = occurrences(body, self.kw)
        self.density = (self.hits / self.words * 100) if self.words else 0.0
        self.in_title = occurrences(article.title, self.kw) > 0
        self.in_desc = occurrences(article.description, self.kw) > 0
        early = " ".join(_words(body)[:EARLY_WORDS])
        self.early = occurrences(early, self.kw) > 0
        self.links_out = [m.group(2) for m in LINK_RE.finditer(body)]
        self.links_in: list[str] = []

    @property
    def path(self) -> str:
        return f"/{self.a.collection}/{self.a.slug}"

    def faults(self) -> list[str]:
        out = []
        if not self.kw:
            out.append("target_keyword ندارد — معلوم نیست برای چه عبارتی نوشته شده.")
            return out
        if self.hits < MIN_OCCURRENCES:
            out.append(
                f"عبارت هدف «{self.kw}» فقط {self.hits} بار در متن آمده. "
                f"کمتر از {MIN_OCCURRENCES} بار یعنی صفحه آشکارا دربارهٔ آن نیست."
            )
        if self.density > DENSITY_CEILING:
            out.append(
                f"چگالی عبارت هدف {self.density:.1f}٪ است و سقف {DENSITY_CEILING}٪ "
                "است. این یعنی متن برای خزنده نوشته شده، و خواننده همین را حس می‌کند."
            )
        if not (self.in_title or self.in_desc):
            out.append(
                f"«{self.kw}» نه در عنوان است نه در توضیح. جستجوکننده پیش از کلیک "
                "فقط همین دو را می‌بیند."
            )
        if not self.early:
            out.append(
                f"«{self.kw}» در {EARLY_WORDS} کلمهٔ اول نیامده. خواننده همان‌جا "
                "تصمیم می‌گیرد این صفحه پرسشش را جواب می‌دهد یا نه."
            )
        if len(self.links_out) < MIN_LINKS_OUT:
            out.append(
                f"{len(self.links_out)} لینک داخلی دارد و کف {MIN_LINKS_OUT} است. "
                "لینک داخلی هم مسیر خواننده است هم مسیر خزنده."
            )
        return out


def _articles(folder: Path):
    """`<slug>.social.md` holds captions, not a page — the build skips those
    and so must this, or the first one aborts the report."""
    for path in sorted(folder.glob("*.md")):
        if not path.name.endswith(".social.md"):
            yield path


PUBLISH_ON_RE = re.compile(r"^publish_on:\s*(\d{4}-\d{2}-\d{2})", re.M)


def _publish_on(path: Path, fallback):
    m = PUBLISH_ON_RE.search(path.read_text(encoding="utf-8"))
    if not m:
        return fallback
    from datetime import date as _date
    return _date.fromisoformat(m.group(1))


def collect() -> list[Report]:
    reports: list[Report] = []
    for path in _articles(ROOT / "content" / "hamzad"):
        a = bc.parse(path)
        # The date the text as it stands today existed, not the date the page
        # first appeared. An article published in August and revised in
        # September may legitimately link to a September article; comparing
        # against the original date would report every such link as broken.
        reports.append(Report(a, "منتشرشده", max(a.published,
                                                 a.updated or a.published)))
    for path in _articles(ROOT / "content" / "queue"):
        a = bc.parse(path)
        reports.append(Report(a, "در صف", _publish_on(path, a.published)))

    by_path = {r.path: r for r in reports}
    for r in reports:
        for target in r.links_out:
            dest = by_path.get(target.rstrip("/"))
            if dest is not None and dest is not r:
                dest.links_in.append(r.path)
    return reports


def render(reports: list[Report]) -> str:
    lines = [
        "# عبارت‌های هدف — فهرست خودکار",
        "",
        "**این فایل با دست نوشته نمی‌شود.** هر بار که محتوا ساخته می‌شود از روی",
        "خودِ مقاله‌ها بازتولید می‌گردد، پس هیچ‌وقت از محتوا عقب نمی‌افتد.",
        "",
        "ساختنش:",
        "",
        "```",
        "python3 tools/seo_report.py",
        "```",
        "",
        "## چه چیزی اندازه گرفته شده",
        "",
        "| ستون | یعنی چه |",
        "|---|---|",
        "| **تکرار** | چند بار عبارت هدف در متن آمده. کمتر از دو بار یعنی صفحه "
        "آشکارا دربارهٔ آن عبارت نیست. |",
        "| **چگالی** | سهم عبارت از کل کلمه‌ها. گوگل سال‌هاست می‌گوید عدد هدفی "
        f"وجود ندارد؛ اینجا فقط **سقف** است ({DENSITY_CEILING}٪). زیر آن، به این "
        "عدد نگاه نکن. |",
        "| **عنوان / توضیح** | آیا عبارت در چیزی که جستجوکننده پیش از کلیک "
        "می‌بیند هست. |",
        "| **آغاز** | آیا در "
        f"{EARLY_WORDS} کلمهٔ اول آمده — جایی که خواننده تصمیم می‌گیرد بماند. |",
        "| **لینک بیرون / درون** | لینک‌های داخلی، در هر دو جهت. ستون «درون» "
        "مهم‌تر است: صفحه‌ای که هیچ صفحهٔ دیگری به آن لینک نداده، فقط از نقشهٔ "
        "سایت پیدا می‌شود و دیرتر از همه خزیده می‌شود. |",
        "",
        "## جدول",
        "",
        "| عبارت هدف | صفحه | وضعیت | کلمه | تکرار | چگالی | عنوان | توضیح | "
        "آغاز | لینک بیرون | لینک درون |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    tick = {True: "✓", False: "—"}
    for r in sorted(reports, key=lambda x: (x.state != "منتشرشده", x.kw)):
        lines.append(
            f"| {r.kw or '—'} | `{r.path}` | {r.state} | {r.words} | {r.hits} | "
            f"{r.density:.1f}٪ | {tick[r.in_title]} | {tick[r.in_desc]} | "
            f"{tick[r.early]} | {len(r.links_out)} | {len(r.links_in)} |"
        )

    orphans = [r for r in reports if not r.links_in]
    lines += ["", "## صفحه‌های بی‌لینکِ ورودی", ""]
    if orphans:
        lines.append(
            "هیچ صفحهٔ دیگری به اینها لینک نداده. تازه‌ترین مقاله طبیعتاً اینجاست "
            "— اما اگر مقاله‌ای هفته‌ها اینجا ماند، یعنی در متنِ مقاله‌های بعدی "
            "به آن ارجاع نداده‌ایم."
        )
        lines.append("")
        for r in orphans:
            lines.append(f"- `{r.path}` — «{r.kw}»")
    else:
        lines.append("هیچ‌کدام. هر صفحه دست‌کم از یک صفحهٔ دیگر لینک گرفته.")

    broken = []
    premature = []
    known = {r.path: r for r in reports}
    for r in reports:
        for target in r.links_out:
            clean = target.rstrip("/").split("#")[0]
            dest = known.get(clean)
            if clean.startswith("/hamzad/") and dest is None:
                broken.append((r.path, target))
            # Linking forward in time is a 404 for every reader until the
            # queue reaches the destination. Easy to write by accident,
            # invisible until someone clicks, and it applies between two
            # queued articles exactly as it does from a live one.
            elif dest is not None and dest.goes_live > r.goes_live:
                premature.append((r.path, clean))
    lines += ["", "## لینک‌های داخلیِ شکسته", ""]
    if broken:
        for src, dst in broken:
            lines.append(f"- `{src}` به `{dst}` لینک داده و چنین صفحه‌ای نیست.")
    else:
        lines.append("هیچ‌کدام.")

    lines += ["", "## لینک به صفحه‌ای که دیرتر منتشر می‌شود", ""]
    if premature:
        lines.append(
            "این‌ها تا روزِ انتشارِ مقصد، برای خواننده ۴۰۴ می‌دهند."
        )
        lines.append("")
        for src, dst in premature:
            lines.append(f"- `{src}` → `{dst}`")
    else:
        lines.append("هیچ‌کدام.")

    faulty = [(r, f) for r in reports for f in [r.faults()] if f]
    lines += ["", "## چیزهایی که باید درست شود", ""]
    if faulty:
        for r, fs in faulty:
            lines.append(f"**`{r.path}`**")
            for f in fs:
                lines.append(f"- {f}")
            lines.append("")
    else:
        lines.append("هیچ‌کدام. همهٔ مقاله‌ها از قاعده‌های بالا رد شده‌اند.")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if an article breaks a rule")
    args = ap.parse_args()

    reports = collect()
    text = render(reports)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")

    faulty = {r.path: r.faults() for r in reports if r.faults()}
    orphans = [r.path for r in reports if not r.links_in]

    # Reported on stdout too, not only in the file — a link that 404s for
    # every reader until next week is worth interrupting someone for.
    by_path = {r.path: r for r in reports}
    premature = []
    for r in reports:
        for link in r.links_out:
            dest = by_path.get(link.rstrip("/").split("#")[0])
            if dest is not None and dest.goes_live > r.goes_live:
                premature.append((r.path, dest.path, dest.goes_live))
    for src, dst, when in premature:
        print(f"  ✗ {src} به {dst} لینک داده که تا {when} منتشر نمی‌شود — "
              "تا آن روز ۴۰۴ است.")
    print(f"{len(reports)} مقاله بررسی شد · {len(faulty)} مورد اشکال · "
          f"{len(orphans)} صفحهٔ بی‌لینکِ ورودی")
    print(f"نوشته شد: {OUT.relative_to(ROOT)}")

    if faulty:
        for path, fs in faulty.items():
            print(f"\n  ✗ {path}")
            for f in fs:
                print(f"      - {f}")
    if (faulty or premature) and args.check:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
